
---
- name: 'Stat check {{ _name }}'
  ansible.builtin.stat:
    path: '{{ _install_path }}'
  register: installed


- name: 'Create install directory {{ _name }}' 
  file:
    path: '{{ _install_path }}'
    state: directory
    owner: root
    group: root
  when: installed.stat.exists == False


- name: 'Downloading {{ _name }}' 
  ansible.builtin.get_url:
    url: '{{ _download_url }}'
    dest: '{{ _install_path }}/{{ _download_file_name }}'
    force: no
  when: installed.stat.exists == False


- name: 'Extracting archive {{ _name }}'
  ansible.builtin.unarchive:
    src: '{{ _install_path }}/{{ _download_file_name }}'
    dest: '{{ _install_path }}'
    owner: root
    group: root
  when: installed.stat.exists == False


- name: 'Removing archive file {{ _name }}'
  ansible.builtin.file:
    path: '{{ _install_path }}/{{ _download_file_name }}'
    state: absent
  when: installed.stat.exists == False


- name: 'Creating symlink for {{ _name }}'
  ansible.builtin.file:
    src: '{{ _install_path }}/{{ _unarchived_dir_name }}'
    dest: '{{ _install_path }}/current'
    state: link
  when: installed.stat.exists == False


- name: 'Updating path for {{ _name }}' 
  ansible.builtin.lineinfile:
    path: '{{ _profile }}'
    line: 'export PATH=$PATH:{{ _install_path }}/current{{ _bin_dir }}'
